Category.create!(:name => "Small Plates", :position => "1")
Category.create!(:name => "Salads and Soups", :position => "2")
Category.create!(:name => "Italian Classics", :position => "3")
Category.create!(:name => "Pasta Specialties", :position => "4")
Category.create!(:name => "Signature Entrees", :position => "5")
Category.create!(:name => "Entrees", :position => "6")
Category.create!(:name => "Desserts", :position => "7")
Category.create!(:name => "Beverages", :position => "8")